begin;

create table if not exists public.chai_shop (
  shop_id bigint generated by default as identity primary key,
  name text not null,
  state text not null,
  country text not null
);

create table if not exists public.chai_reviewer (
  reviewer_id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null
);

create table if not exists public.chai_item (
  chai_id bigint generated by default as identity primary key,
  name text not null,
  iced boolean not null default false,
  shop_id bigint not null references public.chai_shop (shop_id)
);

create table if not exists public.chai_review (
  chai_id bigint not null references public.chai_item (chai_id),
  reviewer_id bigint not null references public.chai_reviewer (reviewer_id),
  rating integer not null check (rating > 0 and rating <= 10),
  primary key (chai_id, reviewer_id)
);

create or replace view public.chai_review_row_details as
select
  cr.chai_id,
  cr.reviewer_id,
  cr.rating,
  ci.name as chai_name,
  ci.iced,
  cs.name as shop_name,
  cs.state as shop_state,
  cs.country as shop_country,
  rv.first_name || ' ' || rv.last_name as reviewer_name
from public.chai_review cr
join public.chai_item ci on ci.chai_id = cr.chai_id
join public.chai_reviewer rv on rv.reviewer_id = cr.reviewer_id
join public.chai_shop cs on cs.shop_id = ci.shop_id;

alter table public.chai_shop enable row level security;
alter table public.chai_reviewer enable row level security;
alter table public.chai_item enable row level security;
alter table public.chai_review enable row level security;

drop policy if exists "Public read chai_shop" on public.chai_shop;
create policy "Public read chai_shop"
on public.chai_shop
for select
using (true);

drop policy if exists "Public insert chai_shop" on public.chai_shop;
create policy "Public insert chai_shop"
on public.chai_shop
for insert
with check (true);

drop policy if exists "Public read chai_reviewer" on public.chai_reviewer;
create policy "Public read chai_reviewer"
on public.chai_reviewer
for select
using (true);

drop policy if exists "Public insert chai_reviewer" on public.chai_reviewer;
create policy "Public insert chai_reviewer"
on public.chai_reviewer
for insert
with check (true);

drop policy if exists "Public read chai_item" on public.chai_item;
create policy "Public read chai_item"
on public.chai_item
for select
using (true);

drop policy if exists "Public insert chai_item" on public.chai_item;
create policy "Public insert chai_item"
on public.chai_item
for insert
with check (true);

drop policy if exists "Public read chai_review" on public.chai_review;
create policy "Public read chai_review"
on public.chai_review
for select
using (true);

drop policy if exists "Public insert chai_review" on public.chai_review;
create policy "Public insert chai_review"
on public.chai_review
for insert
with check (true);

drop policy if exists "Public update chai_review" on public.chai_review;
create policy "Public update chai_review"
on public.chai_review
for update
using (true)
with check (true);

grant usage on schema public to anon, authenticated;
grant select on public.chai_shop to anon, authenticated;
grant select on public.chai_reviewer to anon, authenticated;
grant select on public.chai_item to anon, authenticated;
grant select on public.chai_review to anon, authenticated;
grant select on public.chai_review_row_details to anon, authenticated;
grant insert on public.chai_shop to anon, authenticated;
grant insert on public.chai_reviewer to anon, authenticated;
grant insert on public.chai_item to anon, authenticated;
grant insert on public.chai_review to anon, authenticated;
grant update on public.chai_review to anon, authenticated;

commit;
